-- Create Database & Initialize
CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1: Total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer 
GROUP BY gender;

-- Q2: High-spending discount users
SELECT customer_id, purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
LIMIT 14;

-- Q7: Customer Retention Segmentation
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal' 
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

-- Q8: Top 3 items per product category using window functions
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased    
)
SELECT item_rank, category, item_purchased, total_orders 
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers 
from customer 
where previous_purchases >5  
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer 
group by age_group 
order by total_revenue desc;
